server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/gun_service_db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: info
battle-service-server:
  host: localhost
  port: 8080
uri-builder:
  scheme: http
  host: localhost
  port: 8081
gun-specifications:
  protection-level: 100
  quantity-bursting-cassette: 10
  capacity-bursting-cassette: 10
  quantity-armor-piercing-cassette: 15
  capacity-armor-piercing-cassette: 10